import type { Category, Product, MenuData } from "./types"

export const mockCategories: Category[] = [
  {
    id: "1",
    titlePrimary: "Appetizers",
    titleSecondary: "المقبلات",
    description: "Start your meal with our delicious appetizers",
    image: "/images/categories/appetizers.jpg",
    order: 1,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    titlePrimary: "Main Courses",
    titleSecondary: "الأطباق الرئيسية",
    description: "Our signature main dishes",
    image: "/images/categories/mains.jpg",
    order: 2,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    titlePrimary: "Desserts",
    titleSecondary: "الحلويات",
    description: "Sweet endings to your meal",
    image: "/images/categories/desserts.jpg",
    order: 3,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    titlePrimary: "Beverages",
    titleSecondary: "المشروبات",
    description: "Refreshing drinks and hot beverages",
    image: "/images/categories/beverages.jpg",
    order: 4,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockProducts: Product[] = [
  // Appetizers
  {
    id: "1",
    categoryId: "1",
    titlePrimary: "Hummus Plate",
    titleSecondary: "طبق الحمص",
    description: "Creamy hummus served with fresh vegetables and pita bread",
    ingredients: ["chickpeas", "tahini", "olive oil", "garlic", "lemon juice"],
    price: 12.99,
    image: "/images/products/hummus.jpg",
    isActive: true,
    isFeatured: true,
    order: 1,
    nutritionInfo: {
      calories: 180,
      protein: 8,
      carbs: 20,
      fat: 9,
    },
    allergens: ["sesame"],
    preparationTime: 5,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    categoryId: "1",
    titlePrimary: "Stuffed Grape Leaves",
    titleSecondary: "ورق العنب المحشي",
    description: "Traditional grape leaves stuffed with rice and herbs",
    ingredients: ["grape leaves", "rice", "tomatoes", "onions", "herbs", "olive oil"],
    price: 15.99,
    image: "/images/products/grape-leaves.jpg",
    isActive: true,
    isFeatured: false,
    order: 2,
    nutritionInfo: {
      calories: 220,
      protein: 4,
      carbs: 35,
      fat: 8,
    },
    preparationTime: 10,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  // Main Courses
  {
    id: "3",
    categoryId: "2",
    titlePrimary: "Grilled Chicken Shawarma",
    titleSecondary: "شاورما الدجاج المشوي",
    description: "Tender grilled chicken with garlic sauce and vegetables",
    ingredients: ["chicken breast", "garlic sauce", "lettuce", "tomatoes", "pickles", "pita bread"],
    price: 18.99,
    originalPrice: 22.99,
    image: "/images/products/chicken-shawarma.jpg",
    isActive: true,
    isFeatured: true,
    order: 1,
    nutritionInfo: {
      calories: 450,
      protein: 35,
      carbs: 30,
      fat: 20,
    },
    preparationTime: 15,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    categoryId: "2",
    titlePrimary: "Lamb Kabsa",
    titleSecondary: "كبسة اللحم",
    description: "Traditional spiced rice with tender lamb",
    ingredients: ["basmati rice", "lamb", "onions", "tomatoes", "kabsa spices", "almonds"],
    price: 24.99,
    image: "/images/products/lamb-kabsa.jpg",
    isActive: true,
    isFeatured: true,
    order: 2,
    nutritionInfo: {
      calories: 580,
      protein: 40,
      carbs: 45,
      fat: 25,
    },
    preparationTime: 25,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  // Desserts
  {
    id: "5",
    categoryId: "3",
    titlePrimary: "Baklava",
    titleSecondary: "البقلاوة",
    description: "Layers of phyllo pastry with nuts and honey",
    ingredients: ["phyllo pastry", "pistachios", "walnuts", "honey", "butter"],
    price: 8.99,
    image: "/images/products/baklava.jpg",
    isActive: true,
    isFeatured: false,
    order: 1,
    nutritionInfo: {
      calories: 320,
      protein: 6,
      carbs: 35,
      fat: 18,
    },
    allergens: ["nuts", "gluten"],
    preparationTime: 5,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  // Beverages
  {
    id: "6",
    categoryId: "4",
    titlePrimary: "Fresh Orange Juice",
    titleSecondary: "عصير البرتقال الطازج",
    description: "Freshly squeezed orange juice",
    ingredients: ["fresh oranges"],
    price: 6.99,
    image: "/images/products/orange-juice.jpg",
    isActive: true,
    isFeatured: false,
    order: 1,
    nutritionInfo: {
      calories: 110,
      protein: 2,
      carbs: 26,
      fat: 0,
    },
    preparationTime: 3,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockMenuData: MenuData = {
  categories: mockCategories,
  products: mockProducts,
  lastUpdated: new Date(),
}
